main: net.limework.rediskript.RediSkript
name: RediSkriptPlus
version: 1.3.8
authors: [byPixelTV, Govindas, ham1255, DaemonicKing, limework.net]
api-version: 1.20
depend: [Skript]
commands:
  reloadredis:
    description: "Reload redis configuration & restart the connection."
    permission: rediskript.reload
