main: net.limework.rediskript.RediSkript
name: RediSkript-Skydinse
version: 1.3.6-SNAPSHOT
authors: [Govindas, ham1255, DaemonicKing, limework.net]
api-version: 1.13
depend: [Skript]
commands:
  reloadredis:
    description: "Reload redis configuration & restart the connection."
    permission: reload.redis
